import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { GeneratedCourse, GeneratedLesson } from '@/lib/ai';
import { supabase } from '@/lib/supabase';
import { colors } from '@/constants/theme';

export default function GeneratedLessonScreen() {
  const params = useLocalSearchParams<{ id: string; unit?: string; lesson?: string }>(); const unitIndex = Number(params.unit ?? 0); const lessonIndex = Number(params.lesson ?? 0); const [lesson, setLesson] = useState<GeneratedLesson | null>(null); const [course, setCourse] = useState<GeneratedCourse | null>(null); const [slide, setSlide] = useState(0); const [inQuiz, setInQuiz] = useState(false); const [answers, setAnswers] = useState<Record<number, number>>({});
  useEffect(() => { supabase.from('custom_courses').select('*').eq('id', params.id).single().then(({ data, error }) => { if (error || !data) { Alert.alert('Course unavailable', error?.message ?? 'Please try again.'); router.back(); return; } const next: GeneratedCourse = { id: data.id, title: data.title, description: data.description, category: data.category, difficulty: data.difficulty, learningStyle: data.learning_style, units: data.outline.units ?? [] }; setCourse(next); setLesson(next.units[unitIndex]?.lessons[lessonIndex] ?? null); }); }, [params.id, unitIndex, lessonIndex]);
  if (!lesson || !course) return <SafeAreaView style={s.screen}><ActivityIndicator color="#fff" style={{ flex: 1 }} /></SafeAreaView>;
  const finishQuiz = () => { if (Object.keys(answers).length !== 3) { Alert.alert('Answer every question', 'Choose one answer for each question before continuing.'); return; } const score = lesson.quiz.filter((q, index) => answers[index] === q.correctIndex).length; if (score < 3) Alert.alert(`${score}/3 correct`, 'Review the explanations and retry. You need 3/3 to unlock the next lesson.', [{ text: 'Retry', onPress: () => setAnswers({}) }]); else Alert.alert('3/3 — Mastered', 'Excellent work. The next lesson is now ready.', [{ text: 'Continue', onPress: () => router.replace({ pathname: '/generated-course/[id]', params: { id: course.id } }) }]); };
  if (inQuiz) return <SafeAreaView style={s.screen}><View style={s.nav}><TouchableOpacity onPress={() => setInQuiz(false)}><Ionicons name="chevron-back" size={26} color="#fff" /></TouchableOpacity><Text style={s.navText}>Mastery check</Text><View style={{ width: 26 }} /></View><ScrollView contentContainerStyle={s.quizContent}><Text style={s.quizTitle}>Show what you learned</Text>{lesson.quiz.map((q, qIndex) => <View key={q.question} style={s.question}><Text style={s.questionNumber}>QUESTION {qIndex + 1} OF 3</Text><Text style={s.questionText}>{q.question}</Text>{q.options.map((option, optionIndex) => <Pressable key={option} onPress={() => setAnswers(current => ({ ...current, [qIndex]: optionIndex }))} style={[s.option, answers[qIndex] === optionIndex && s.optionActive]}><Text style={[s.optionText, answers[qIndex] === optionIndex && s.optionTextActive]}>{option}</Text></Pressable>)}</View>)}</ScrollView><View style={s.footer}><TouchableOpacity style={s.continue} onPress={finishQuiz}><Text style={s.continueText}>Check and continue</Text></TouchableOpacity></View></SafeAreaView>;
  const card = lesson.slides[slide]; const isLast = slide === lesson.slides.length - 1;
  return <SafeAreaView style={s.screen}><View style={s.nav}><TouchableOpacity onPress={() => router.back()}><Ionicons name="close" size={25} color="#fff" /></TouchableOpacity><Text style={s.navText}>{slide + 1} of {lesson.slides.length} · {lesson.estimatedMinutes} min</Text><View style={{ width: 25 }} /></View><View style={s.progress}><View style={[s.progressFill, { width: `${((slide + 1) / lesson.slides.length) * 100}%` }]} /></View><ScrollView contentContainerStyle={s.cardContent}><Text style={s.eyebrow}>{course.category.toUpperCase()} · {lesson.title.toUpperCase()}</Text><Text style={s.cardTitle}>{card.title}</Text><Text style={s.body}>{card.body}</Text>{card.keyPoint && <View style={s.keyPoint}><Text style={s.keyLabel}>KEY IDEA</Text><Text style={s.keyText}>{card.keyPoint}</Text></View>}</ScrollView><View style={s.footer}><TouchableOpacity style={s.continue} onPress={() => isLast ? setInQuiz(true) : setSlide(value => value + 1)}><Text style={s.continueText}>{isLast ? 'Start mastery check' : 'Continue'}</Text></TouchableOpacity></View></SafeAreaView>;
}
const s = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#000' }, nav: { height: 54, paddingHorizontal: 20, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, navText: { color: colors.secondary, fontSize: 12, fontWeight: '600' }, progress: { height: 3, marginHorizontal: 20, backgroundColor: '#1d1d1d' }, progressFill: { height: 3, backgroundColor: '#fff' }, cardContent: { padding: 26, paddingTop: 58, paddingBottom: 130 }, eyebrow: { color: colors.secondary, fontSize: 10, letterSpacing: 1.5, fontWeight: '700' }, cardTitle: { color: '#fff', fontSize: 34, lineHeight: 39, fontWeight: '700', letterSpacing: -.8, marginTop: 15 }, body: { color: '#c4c4c4', fontSize: 18, lineHeight: 29, marginTop: 28 }, keyPoint: { borderLeftWidth: 2, borderLeftColor: '#fff', paddingLeft: 16, marginTop: 36 }, keyLabel: { color: colors.tertiary, fontSize: 9, letterSpacing: 1.5, fontWeight: '700' }, keyText: { color: '#ddd', fontSize: 15, lineHeight: 22, marginTop: 8 }, quizContent: { padding: 24, paddingBottom: 130 }, quizTitle: { color: '#fff', fontSize: 31, fontWeight: '700', marginTop: 25, marginBottom: 34 }, question: { marginBottom: 38 }, questionNumber: { color: colors.tertiary, fontSize: 9, letterSpacing: 1.5, fontWeight: '700' }, questionText: { color: '#fff', fontSize: 19, lineHeight: 26, fontWeight: '600', marginTop: 9, marginBottom: 14 }, option: { minHeight: 52, borderRadius: 12, borderWidth: 1, borderColor: '#292929', justifyContent: 'center', paddingHorizontal: 15, marginTop: 9 }, optionActive: { backgroundColor: '#fff', borderColor: '#fff' }, optionText: { color: '#ddd', fontSize: 14 }, optionTextActive: { color: '#000', fontWeight: '600' }, footer: { position: 'absolute', left: 0, right: 0, bottom: 0, padding: 20, backgroundColor: '#000', borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: '#222' }, continue: { height: 56, borderRadius: 28, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center' }, continueText: { color: '#000', fontSize: 16, fontWeight: '700' } });
