import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { colors } from '@/constants/theme';
import { feed } from '@/data/content';
import { goBack } from '@/lib/navigation';

export default function Comments() {
  const { id } = useLocalSearchParams<{ id: string }>(); const post = feed.find(item => item.id === id) ?? feed[0];
  const [draft, setDraft] = useState(''); const [comments, setComments] = useState([{ id: '1', author: 'Maya', body: 'The practical example made this click for me.' }]);
  const submit = () => { const body = draft.trim(); if (!body) return; setComments(v => [...v, { id: String(Date.now()), author: 'Rahul', body }]); setDraft(''); };
  return <SafeAreaView style={styles.screen}><KeyboardAvoidingView style={styles.screen} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={styles.nav}><Pressable onPress={() => goBack()} style={styles.navButton}><Ionicons name="chevron-back" size={27} color="#fff" /></Pressable><Text style={styles.navTitle}>Comments</Text><View style={styles.navButton} /></View><ScrollView contentContainerStyle={styles.content}><Text style={styles.postTitle}>{post.title}</Text>{comments.map(comment => <View key={comment.id} style={styles.comment}><View style={styles.avatar}><Text style={styles.avatarText}>{comment.author[0]}</Text></View><View style={{ flex: 1 }}><Text style={styles.author}>{comment.author}</Text><Text style={styles.body}>{comment.body}</Text></View></View>)}</ScrollView><View style={styles.composer}><TextInput value={draft} onChangeText={setDraft} placeholder="Add a thoughtful comment" placeholderTextColor={colors.secondary} style={styles.input} /><Pressable accessibilityLabel="Post comment" disabled={!draft.trim()} onPress={submit} style={[styles.send, !draft.trim() && { opacity: .35 }]}><Ionicons name="arrow-up" size={18} color="#000" /></Pressable></View></KeyboardAvoidingView></SafeAreaView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#000' }, nav: { height: 54, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: colors.border, paddingHorizontal: 10 }, navButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }, navTitle: { color: '#fff', fontSize: 15, fontWeight: '600' }, content: { padding: 20 }, postTitle: { color: '#fff', fontSize: 19, fontWeight: '700', paddingBottom: 18, borderBottomWidth: 1, borderBottomColor: colors.border }, comment: { flexDirection: 'row', gap: 12, paddingVertical: 18, borderBottomWidth: 1, borderBottomColor: colors.border }, avatar: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center' }, avatarText: { color: '#000', fontWeight: '700' }, author: { color: '#fff', fontSize: 13, fontWeight: '600' }, body: { color: 'rgba(255,255,255,.76)', fontSize: 14, lineHeight: 20, marginTop: 4 }, composer: { borderTopWidth: 1, borderTopColor: colors.border, padding: 12, flexDirection: 'row', gap: 10, alignItems: 'center' }, input: { flex: 1, height: 44, borderRadius: 22, backgroundColor: colors.elevated, color: '#fff', paddingHorizontal: 16 }, send: { width: 38, height: 38, borderRadius: 19, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center' } });
