import { Ionicons } from '@expo/vector-icons';
import * as Haptics from 'expo-haptics';
import { router } from 'expo-router';
import { useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { colors } from '@/constants/theme';
import { supabase } from '@/lib/supabase';
import { OnboardingProfile, useAppState } from '@/state/AppState';

const interests = ['Finance', 'AI & Tech', 'Business', 'History', 'Science', 'Psychology', 'Health', 'Politics', 'Philosophy', 'Career', 'Cooking', 'Sports', 'Culture'];
const subtopics: Record<string, string[]> = {
  Finance: ['Stocks', 'Options', 'Economics', 'Trading', 'Personal Finance', 'Companies'],
  'AI & Tech': ['Artificial Intelligence', 'Startups', 'Coding', 'Robotics', 'Cybersecurity', 'Big Tech'],
  Business: ['Entrepreneurship', 'Management', 'Marketing', 'Strategy', 'Leadership', 'Companies'],
  History: ['Ancient History', 'World Wars', 'U.S. History', 'Empires', 'Politics', 'Historical Figures'],
  Science: ['Physics', 'Biology', 'Chemistry', 'Space', 'Climate', 'Medicine'],
  Psychology: ['Behavior', 'Memory', 'Habits', 'Relationships', 'Mental Health', 'Decision Making'],
  Health: ['Nutrition', 'Fitness', 'Sleep', 'Longevity', 'Mental Health', 'Medicine'],
  Politics: ['U.S. Politics', 'World Politics', 'Policy', 'Elections', 'Geopolitics', 'Institutions'],
  Philosophy: ['Ethics', 'Logic', 'Meaning', 'Stoicism', 'Political Philosophy', 'Great Thinkers'],
  Career: ['Leadership', 'Communication', 'Productivity', 'Negotiation', 'Networking', 'Job Skills'],
  Cooking: ['Techniques', 'Nutrition', 'World Cuisines', 'Baking', 'Ingredients', 'Food Science'],
  Sports: ['Performance', 'Strategy', 'Sports Science', 'History', 'Business of Sports', 'Athletes'],
  Culture: ['Art', 'Music', 'Film', 'Books', 'Society', 'Ideas'],
};
const levels = [{ title: 'Beginner', detail: "I'm just getting started" }, { title: 'Intermediate', detail: 'I know the basics' }, { title: 'Advanced', detail: 'I want deeper content' }] as const;
const goals = ['Learn something every day', 'Replace mindless scrolling', 'Get ahead in my career', 'Understand the world & news', 'Master specific subjects', 'Explore new things'];
const stylesList = ['Short-form content', 'Quick lessons', 'Visual stories', 'Courses', 'Articles', 'Audio', 'Quizzes'];

export default function Onboarding() {
  const [step, setStep] = useState(0); const [selectedInterests, setSelectedInterests] = useState<string[]>([]); const [selectedSubtopics, setSelectedSubtopics] = useState<Record<string, string[]>>({}); const [level, setLevel] = useState<OnboardingProfile['level']>(); const [selectedGoals, setSelectedGoals] = useState<string[]>([]); const [learningStyles, setLearningStyles] = useState<string[]>([]); const [saving, setSaving] = useState(false); const { finishOnboarding } = useAppState();
  const availableSubtopics = useMemo(() => selectedInterests.flatMap(topic => (subtopics[topic] ?? []).map(item => ({ topic, item }))), [selectedInterests]);
  const toggle = (value: string, values: string[], setter: (next: string[]) => void) => { Haptics.selectionAsync().catch(() => undefined); setter(values.includes(value) ? values.filter(item => item !== value) : [...values, value]); };
  const valid = step === 0 ? selectedInterests.length >= 3 : step === 1 ? Object.values(selectedSubtopics).flat().length > 0 : step === 2 ? Boolean(level) : step === 3 ? selectedGoals.length > 0 : learningStyles.length > 0;
  const next = async () => { if (!valid) return; if (step < 4) { setStep(step + 1); return; } setSaving(true); const profile: OnboardingProfile = { interests: selectedInterests, subtopics: selectedSubtopics, level: level!, goals: selectedGoals, learningStyles }; try { const { data: { user } } = await supabase.auth.getUser(); if (user && !user.is_anonymous) { const { error } = await supabase.from('users').update({ onboarding_complete: true, current_level: level!, detailed_interests: selectedSubtopics, goals: selectedGoals, learning_styles: learningStyles }).eq('id', user.id); if (error) throw error; } finishOnboarding(profile); router.replace('/(tabs)/explore'); } catch (error) { Alert.alert('Could not save your choices', error instanceof Error ? error.message : 'Please try again.'); } finally { setSaving(false); } };
  const headings = [['What are you interested in?', 'Choose at least 3'], ['What do you want to learn about?', 'Choose as many as you like'], ["What's your current level?", 'Choose one'], ['What are your goals?', 'Select all that apply'], ['How do you like to learn?', 'Select all that apply']];
  return <SafeAreaView style={s.screen}><View style={s.header}>{step > 0 ? <TouchableOpacity onPress={() => setStep(step - 1)}><Ionicons name="chevron-back" color="#fff" size={27} /></TouchableOpacity> : <View style={s.headerSpace} />}<Text style={s.progress}>{step + 1} of 5</Text><View style={s.headerSpace} /></View><View style={s.track}><View style={[s.trackFill, { width: `${(step + 1) * 20}%` }]} /></View><ScrollView contentContainerStyle={s.content}><Text style={s.title}>{headings[step][0]}</Text><Text style={s.subtitle}>{headings[step][1]}</Text>
    {step === 0 && <View style={s.chips}>{interests.map(item => <Choice key={item} title={item} active={selectedInterests.includes(item)} onPress={() => toggle(item, selectedInterests, setSelectedInterests)} />)}</View>}
    {step === 1 && <View style={s.groups}>{selectedInterests.map(topic => <View key={topic}><Text style={s.groupTitle}>{topic}</Text><View style={s.chips}>{availableSubtopics.filter(entry => entry.topic === topic).map(({ item }) => <Choice key={`${topic}-${item}`} title={item} active={(selectedSubtopics[topic] ?? []).includes(item)} onPress={() => setSelectedSubtopics(current => ({ ...current, [topic]: (current[topic] ?? []).includes(item) ? current[topic].filter(value => value !== item) : [...(current[topic] ?? []), item] }))} />)}</View></View>)}</View>}
    {step === 2 && <View style={s.cards}>{levels.map(item => <Pressable key={item.title} onPress={() => setLevel(item.title)} style={[s.card, level === item.title && s.activeCard]}><View style={[s.radio, level === item.title && s.activeRadio]}>{level === item.title && <View style={s.dot} />}</View><View><Text style={s.cardTitle}>{item.title}</Text><Text style={s.cardDetail}>{item.detail}</Text></View></Pressable>)}</View>}
    {step === 3 && <View style={s.cards}>{goals.map(item => <CheckRow key={item} title={item} active={selectedGoals.includes(item)} onPress={() => toggle(item, selectedGoals, setSelectedGoals)} />)}</View>}
    {step === 4 && <View style={s.cards}>{stylesList.map(item => <CheckRow key={item} title={item} active={learningStyles.includes(item)} onPress={() => toggle(item, learningStyles, setLearningStyles)} />)}</View>}
  </ScrollView><View style={s.footer}><TouchableOpacity disabled={!valid || saving} onPress={next} style={[s.button, (!valid || saving) && s.disabled]}>{saving ? <ActivityIndicator color="#000" /> : <Text style={s.buttonText}>{step === 4 ? 'Finish' : 'Continue'}</Text>}</TouchableOpacity></View></SafeAreaView>;
}
function Choice({ title, active, onPress }: { title: string; active: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={[s.choice, active && s.activeChoice]}><Text style={[s.choiceText, active && s.activeChoiceText]}>{title}</Text></Pressable>; }
function CheckRow({ title, active, onPress }: { title: string; active: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={[s.checkRow, active && s.activeCard]}><View style={[s.checkbox, active && s.activeCheckbox]}>{active && <Ionicons name="checkmark" size={16} color="#000" />}</View><Text style={s.cardTitle}>{title}</Text></Pressable>; }
const s = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.black }, header: { height: 52, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, headerSpace: { width: 27 }, progress: { color: colors.secondary, fontSize: 13, fontWeight: '600' }, track: { height: 2, backgroundColor: '#1D1D1D' }, trackFill: { height: 2, backgroundColor: '#fff' }, content: { padding: 24, paddingTop: 54, paddingBottom: 30 }, title: { color: colors.white, fontSize: 34, lineHeight: 40, fontWeight: '700', letterSpacing: -1 }, subtitle: { color: colors.secondary, fontSize: 16, marginTop: 10, marginBottom: 34 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, choice: { minHeight: 48, paddingHorizontal: 18, borderRadius: 24, borderWidth: 1, borderColor: '#2A2A2A', justifyContent: 'center' }, activeChoice: { backgroundColor: '#fff', borderColor: '#fff' }, choiceText: { color: '#D0D0D0', fontSize: 15 }, activeChoiceText: { color: '#000', fontWeight: '700' }, groups: { gap: 28 }, groupTitle: { color: '#fff', fontSize: 19, fontWeight: '700', marginBottom: 14 }, cards: { gap: 12 }, card: { minHeight: 82, borderRadius: 16, borderWidth: 1, borderColor: '#292929', padding: 17, flexDirection: 'row', alignItems: 'center', gap: 15 }, activeCard: { borderColor: '#fff', backgroundColor: '#101010' }, radio: { width: 24, height: 24, borderRadius: 12, borderWidth: 1.5, borderColor: '#777', alignItems: 'center', justifyContent: 'center' }, activeRadio: { borderColor: '#fff' }, dot: { width: 12, height: 12, borderRadius: 6, backgroundColor: '#fff' }, cardTitle: { color: '#fff', fontSize: 16, fontWeight: '600' }, cardDetail: { color: colors.secondary, fontSize: 14, marginTop: 5 }, checkRow: { minHeight: 62, borderRadius: 14, borderWidth: 1, borderColor: '#292929', paddingHorizontal: 17, flexDirection: 'row', alignItems: 'center', gap: 14 }, checkbox: { width: 23, height: 23, borderRadius: 5, borderWidth: 1.5, borderColor: '#777', alignItems: 'center', justifyContent: 'center' }, activeCheckbox: { backgroundColor: '#fff', borderColor: '#fff' }, footer: { paddingHorizontal: 20, paddingVertical: 12, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: '#222' }, button: { height: 56, borderRadius: 28, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff' }, disabled: { opacity: .35 }, buttonText: { color: '#000', fontSize: 16, fontWeight: '700' } });
