import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { colors } from '@/constants/theme';
import { GeneratedCourse } from '@/lib/ai';
import { supabase } from '@/lib/supabase';

export default function GeneratedCourseScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const [course, setCourse] = useState<GeneratedCourse | null>(null); const [error, setError] = useState('');
  useEffect(() => { supabase.from('custom_courses').select('*').eq('id', id).single().then(({ data, error: queryError }) => { if (queryError || !data) setError(queryError?.message ?? 'Course not found.'); else setCourse({ id: data.id, title: data.title, description: data.description, category: data.category, difficulty: data.difficulty, learningStyle: data.learning_style, units: data.outline.units ?? [] }); }); }, [id]);
  if (!course) return <SafeAreaView style={s.screen}><View style={s.nav}><TouchableOpacity onPress={() => router.back()}><Ionicons name="chevron-back" size={26} color="#fff" /></TouchableOpacity><Text style={s.navTitle}>Custom course</Text><View style={s.spacer} /></View><View style={s.center}>{error ? <Text style={s.error}>{error}</Text> : <ActivityIndicator color="#fff" />}</View></SafeAreaView>;
  const lessonCount = course.units.reduce((sum, unit) => sum + unit.lessons.length, 0);
  const start = () => router.push({ pathname: '/generated-lesson/[id]', params: { id: course.id, unit: '0', lesson: '0' } });
  return <SafeAreaView style={s.screen}><View style={s.nav}><TouchableOpacity onPress={() => router.back()}><Ionicons name="chevron-back" size={26} color="#fff" /></TouchableOpacity><Text style={s.navTitle}>Custom course</Text><View style={s.spacer} /></View><ScrollView contentContainerStyle={s.content}><Text style={s.eyebrow}>{course.category.toUpperCase()}</Text><Text style={s.title}>{course.title}</Text><Text style={s.description}>{course.description}</Text><View style={s.meta}><Text style={s.metaText}>{course.difficulty}</Text><Text style={s.metaText}>{course.learningStyle}</Text><Text style={s.metaText}>{lessonCount} lessons</Text></View><Text style={s.heading}>Course path</Text>{course.units.map((unit, unitIndex) => <View key={`${unit.title}-${unitIndex}`} style={s.unit}><Text style={s.unitLabel}>UNIT {unitIndex + 1}</Text><Text style={s.unitTitle}>{unit.title}</Text><Text style={s.unitObjective}>{unit.description}</Text>{unit.lessons.map((lesson, lessonIndex) => { const active = unitIndex === 0 && lessonIndex === 0; return <TouchableOpacity disabled={!active} onPress={start} key={`${lesson.title}-${lessonIndex}`} style={s.lesson}><View style={[s.number, !active && s.locked]}><Text style={[s.numberText, !active && s.numberDim]}>{lessonIndex + 1}</Text></View><View style={s.lessonText}><Text style={[s.lessonTitle, !active && s.dim]}>{lesson.title}</Text><Text style={s.lessonMeta}>{lesson.estimatedMinutes} min · {lesson.slides.length} parts</Text></View><Ionicons name={active ? 'play' : 'lock-closed'} size={active ? 17 : 14} color={active ? '#fff' : '#555'} /></TouchableOpacity>; })}</View>)}</ScrollView><View style={s.footer}><TouchableOpacity style={s.start} onPress={start}><Text style={s.startText}>Start</Text></TouchableOpacity></View></SafeAreaView>;
}
const s = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#000' }, nav: { height: 54, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, navTitle: { color: colors.secondary, fontSize: 14, fontWeight: '600' }, spacer: { width: 26 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 28 }, error: { color: colors.secondary, textAlign: 'center' }, content: { padding: 24, paddingBottom: 130 }, eyebrow: { color: colors.secondary, fontSize: 11, letterSpacing: 2, fontWeight: '700', marginTop: 24 }, title: { color: '#fff', fontSize: 37, lineHeight: 42, fontWeight: '700', letterSpacing: -1, marginTop: 12 }, description: { color: colors.secondary, fontSize: 16, lineHeight: 24, marginTop: 13 }, meta: { flexDirection: 'row', gap: 8, marginTop: 20, flexWrap: 'wrap' }, metaText: { color: '#ccc', borderWidth: 1, borderColor: '#2a2a2a', paddingVertical: 7, paddingHorizontal: 11, borderRadius: 8, fontSize: 12 }, heading: { color: '#fff', fontSize: 25, fontWeight: '700', marginTop: 42, marginBottom: 18 }, unit: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: '#292929', paddingTop: 22, marginBottom: 34 }, unitLabel: { color: colors.tertiary, fontSize: 10, letterSpacing: 2, fontWeight: '700' }, unitTitle: { color: '#fff', fontSize: 21, fontWeight: '700', marginTop: 8 }, unitObjective: { color: colors.secondary, fontSize: 14, lineHeight: 20, marginTop: 6, marginBottom: 16 }, lesson: { minHeight: 68, flexDirection: 'row', alignItems: 'center', gap: 14, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: '#222' }, number: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center' }, locked: { backgroundColor: '#181818' }, numberText: { color: '#000', fontSize: 12, fontWeight: '700' }, numberDim: { color: '#666' }, lessonText: { flex: 1 }, lessonTitle: { color: '#fff', fontSize: 15, fontWeight: '600' }, lessonMeta: { color: colors.tertiary, fontSize: 11, marginTop: 4 }, dim: { color: '#666' }, footer: { position: 'absolute', left: 0, right: 0, bottom: 0, padding: 20, backgroundColor: '#000', borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: '#222' }, start: { height: 56, borderRadius: 28, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center' }, startText: { color: '#000', fontSize: 17, fontWeight: '700' } });
