create extension if not exists pgcrypto;

create table public.users (id uuid primary key references auth.users(id) on delete cascade, username text unique, display_name text, avatar_path text, created_at timestamptz not null default now());
create table public.topics (id uuid primary key default gen_random_uuid(), slug text not null unique, name text not null, artwork_path text);
create table public.user_interests (user_id uuid not null references public.users(id) on delete cascade, topic_id uuid not null references public.topics(id) on delete cascade, weight real not null default 1 check (weight between 0 and 5), primary key (user_id, topic_id));
create table public.learning_paths (id uuid primary key default gen_random_uuid(), slug text unique not null, title text not null, description text not null, topic_id uuid references public.topics(id), published boolean not null default false);
create table public.lessons (id uuid primary key default gen_random_uuid(), path_id uuid not null references public.learning_paths(id) on delete cascade, position integer not null check (position > 0), title text not null, xp integer not null default 25 check (xp >= 0), unique(path_id, position));
create table public.lesson_blocks (id uuid primary key default gen_random_uuid(), lesson_id uuid not null references public.lessons(id) on delete cascade, position integer not null, kind text not null check (kind in ('text','image','video','question')), body jsonb not null default '{}', unique(lesson_id, position));
create table public.sources (id uuid primary key default gen_random_uuid(), name text not null, url text, credibility_score real not null default .5 check (credibility_score between 0 and 1));
create table public.content (id uuid primary key default gen_random_uuid(), slug text unique not null, title text not null, description text not null, media_path text, source_id uuid references public.sources(id), learning_path_id uuid references public.learning_paths(id), difficulty real not null default .5 check (difficulty between 0 and 1), quality_score real not null default .5 check (quality_score between 0 and 1), published_at timestamptz, created_at timestamptz not null default now());
create table public.content_topics (content_id uuid references public.content(id) on delete cascade, topic_id uuid references public.topics(id) on delete cascade, relevance real not null default 1, primary key(content_id, topic_id));
create table public.content_events (id bigint generated always as identity primary key, user_id uuid not null references public.users(id) on delete cascade, content_id uuid not null references public.content(id) on delete cascade, event_type text not null check (event_type in ('impression','complete','skip','like','unlike','save','unsave','share','open_learn')), watch_ratio real check (watch_ratio between 0 and 1), created_at timestamptz not null default now());
create table public.user_learning_progress (user_id uuid references public.users(id) on delete cascade, lesson_id uuid references public.lessons(id) on delete cascade, completed_at timestamptz, score real check (score between 0 and 1), primary key(user_id, lesson_id));
create table public.user_stats (user_id uuid primary key references public.users(id) on delete cascade, xp integer not null default 0 check (xp >= 0), streak_days integer not null default 0 check (streak_days >= 0), lessons_completed integer not null default 0 check (lessons_completed >= 0), updated_at timestamptz not null default now());
create table public.likes (user_id uuid references public.users(id) on delete cascade, content_id uuid references public.content(id) on delete cascade, created_at timestamptz not null default now(), primary key(user_id, content_id));
create table public.saves (user_id uuid references public.users(id) on delete cascade, content_id uuid references public.content(id) on delete cascade, created_at timestamptz not null default now(), primary key(user_id, content_id));
create table public.news_stories (id uuid primary key default gen_random_uuid(), slug text unique not null, headline text not null, summary text not null, image_path text, happened text, why_it_matters text, background text, what_to_watch text, learning_path_id uuid references public.learning_paths(id), published_at timestamptz, created_at timestamptz not null default now());

create index content_published_idx on public.content (published_at desc) where published_at is not null;
create index content_events_user_created_idx on public.content_events (user_id, created_at desc);
create index content_topics_topic_idx on public.content_topics (topic_id, content_id);

alter table public.users enable row level security; alter table public.topics enable row level security; alter table public.user_interests enable row level security; alter table public.content enable row level security; alter table public.content_topics enable row level security; alter table public.content_events enable row level security; alter table public.learning_paths enable row level security; alter table public.lessons enable row level security; alter table public.lesson_blocks enable row level security; alter table public.user_learning_progress enable row level security; alter table public.user_stats enable row level security; alter table public.likes enable row level security; alter table public.saves enable row level security; alter table public.news_stories enable row level security; alter table public.sources enable row level security;

create policy "public topics" on public.topics for select to anon, authenticated using (true); create policy "public published content" on public.content for select to anon, authenticated using (published_at <= now()); create policy "public content topics" on public.content_topics for select to anon, authenticated using (true); create policy "public paths" on public.learning_paths for select to anon, authenticated using (published); create policy "public lessons" on public.lessons for select to anon, authenticated using (exists (select 1 from public.learning_paths p where p.id = path_id and p.published)); create policy "public lesson blocks" on public.lesson_blocks for select to anon, authenticated using (exists (select 1 from public.lessons l join public.learning_paths p on p.id=l.path_id where l.id=lesson_id and p.published)); create policy "public stories" on public.news_stories for select to anon, authenticated using (published_at <= now()); create policy "public sources" on public.sources for select to anon, authenticated using (true);
create policy "own profile select" on public.users for select to authenticated using ((select auth.uid()) = id); create policy "own profile update" on public.users for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);
create policy "own interests" on public.user_interests for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id); create policy "own events" on public.content_events for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id); create policy "own progress" on public.user_learning_progress for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id); create policy "own stats" on public.user_stats for select to authenticated using ((select auth.uid()) = user_id); create policy "own likes" on public.likes for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id); create policy "own saves" on public.saves for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = '' as $$ begin insert into public.users(id, display_name) values(new.id, coalesce(new.raw_user_meta_data->>'full_name','Learner')); insert into public.user_stats(user_id) values(new.id); return new; end; $$;
revoke execute on function public.handle_new_user() from public, anon, authenticated;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

insert into storage.buckets(id, name, public) values ('content','content',true), ('avatars','avatars',false) on conflict (id) do nothing;
create policy "public content media read" on storage.objects for select to anon, authenticated using (bucket_id='content');
create policy "avatar owner read" on storage.objects for select to authenticated using (bucket_id='avatars' and owner_id=(select auth.uid()::text));
create policy "avatar owner insert" on storage.objects for insert to authenticated with check (bucket_id='avatars' and (storage.foldername(name))[1]=(select auth.uid()::text));
create policy "avatar owner update" on storage.objects for update to authenticated using (bucket_id='avatars' and owner_id=(select auth.uid()::text)) with check (bucket_id='avatars' and owner_id=(select auth.uid()::text));

grant usage on schema public to anon, authenticated; grant select on public.topics, public.content, public.content_topics, public.learning_paths, public.lessons, public.lesson_blocks, public.news_stories, public.sources to anon, authenticated; grant select, update on public.users to authenticated; grant select, insert, update, delete on public.user_interests, public.content_events, public.user_learning_progress, public.likes, public.saves to authenticated; grant select on public.user_stats to authenticated;
